import type { Metadata } from "next";
import { Annie_Use_Your_Telescope } from "next/font/google";
import "../style/globals.css";
import "../style/custom.css";


const inter = Annie_Use_Your_Telescope({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Rishvan M",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
